District_Forests/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dfm/urls.py
"""District_Forests URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
    1. Add an import:  from my_app import views
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('allauth.urls')),
    path('transport-permit/', include('permit.urls')),
    path('user/', include('user.urls')),
    path('harvesting-permit/', include('harvest.urls'))
]

permit/models.py
from datetime import timedelta

from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.shortcuts import get_object_or_404, reverse
from django.utils.translation import gettext_lazy as _

from user.models import Officer

from .utils import end_date_default, permit_code, start_date_default

User = get_user_model()


class Province(models.Model):
    code = models.CharField(max_length=2, blank=True, null=True)
    name = models.CharField(blank=False, null=False, max_length=255)

    def __str__(self):
        return self.name


class District(models.Model):
    code = models.CharField(max_length=2, blank=True, null=True)
    province = models.ForeignKey(
        Province, on_delete=models.CASCADE, null=False, blank=False, related_name='districts')
    name = models.CharField(blank=False, null=False, max_length=255)

    def __str__(self):
        return self.name


class Sector(models.Model):
    code = models.CharField(max_length=2, blank=True, null=True)
    district = models.ForeignKey(
        District, on_delete=models.CASCADE, blank=False, null=False, related_name='sectors')
    name = models.CharField(max_length=100, unique=False,
                            null=False, blank=False)

    def __str__(self):
        return self.name


class Cell(models.Model):
    code = models.CharField(max_length=2, blank=True, null=True)
    sector = models.ForeignKey(
        Sector, on_delete=models.CASCADE, blank=False, null=False, related_name='cells')
    name = models.CharField(max_length=200, blank=False,
                            null=False, unique=False)

    def __str__(self):
        return self.name


class Village(models.Model):
    code = models.CharField(max_length=2, blank=True, null=True)
    cell = models.ForeignKey(
        Cell, on_delete=models.CASCADE, blank=False, null=False, related_name='villages')
    name = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.name


class Address(models.Model):
    code = models.CharField(max_length=20, blank=True, null=True)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    cell = models.ForeignKey(
        Cell, null=True, blank=True, on_delete=models.SET_NULL)
    village = models.ForeignKey(
        Village, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.province.name

    def code_gen(self):
        code = '%s/%s/%s' % (self.province.code,
                             self.district.code, self.sector.code)
        if self.cell:
            code = '%s/%s/%s/%s/' % (self.province.code,
                                     self.district.code, self.sector.code, self.cell.code)

        return code

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.code_gen()
        super().save(*args, **kwargs)


class Mayor(models.Model):
    name = models.CharField(max_length=255)


class Category(models.Model):
    cats = (('AM', 'Amakara'), ('AS', 'Amasiteri'),
            ('IM', 'Imbaho'), ('IB', 'Ibiti'))
    name = models.CharField(_('Ubwoko'), max_length=2, choices=cats)
    measure = models.CharField(
        _('Urugero'), max_length=50, blank=True, default='Amasiteri')
    minimum = models.IntegerField(_('Ingano ntoya'), default=10)

    def __str__(self):
        return self.get_name_display()

    class Meta:
        verbose_name_plural = 'categories'


class Requestor(models.Model):
    names = models.CharField(
        _('Amazina'), max_length=255, blank=False, null=False)
    nid = models.CharField(
        _('Indangamuntu'), max_length=21, blank=True, null=True)
    telephone = models.CharField(
        _('telephone'), max_length=15, blank=True, null=True)
    r_province = models.ForeignKey(
        Province, on_delete=models.SET, null=True, verbose_name='Intara')
    r_district = models.ForeignKey(
        District, on_delete=models.SET, null=True, verbose_name='Akarere')
    r_sector = models.ForeignKey(
        Sector, on_delete=models.SET, null=True, verbose_name='Umurenge')
    r_cell = models.ForeignKey(
        Cell, on_delete=models.SET_NULL, null=True, verbose_name='Akagali')
    # r_village = models.ForeignKey(
    #     Village, on_delete=models.SET_NULL, null=True, verbose_name='Umudugudu')

    def __str__(self):
        return self.names


class TransportVehicle(models.Model):
    cats = (('FS', 'FUSSO'), ('BN', 'BEN'), ('DH', 'DAIHATSU'))
    vehicle = models.CharField(
        _('Ubwoko'), max_length=20, choices=cats, default='FS')
    plate = models.CharField(_('Plake'), max_length=10)
    max_q = models.PositiveIntegerField(
        blank=True, null=True, verbose_name='Ibyo itwara(Toni)')
    driver = models.CharField(_('Umushoferi'), max_length=255)
    driver_tel = models.CharField(_("Nimero y'umushoferi"), max_length=255)

    def __str__(self):
        return self.driver


class OriginLocation(models.Model):
    code = models.CharField(max_length=30, blank=True,
                            null=True, editable=False)
    l_province = models.ForeignKey(
        Province, on_delete=models.CASCADE, verbose_name='Intara')
    l_district = models.ForeignKey(
        District, on_delete=models.CASCADE, verbose_name='Akarere')
    l_sector = models.ForeignKey(
        Sector, on_delete=models.CASCADE, verbose_name='Umurenge')
    l_cell = models.ForeignKey(
        Cell, null=True, on_delete=models.SET_NULL, verbose_name='Akagali')
    # l_village = models.ForeignKey(
    # Village, null=True, on_delete=models.SET_NULL, verbose_name='Umudugudu')

    def __str__(self):
        return self.code

    def code_gen(self):
        code = '%s/%s/%s' % (self.l_province.code,
                             self.l_district.code, self.l_sector.code)
        if self.l_cell:
            code = '%s/%s/%s/%s/' % (self.l_province.code,
                                     self.l_district.code, self.l_sector.code, self.l_cell.code)
        return code

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.code_gen()
        super().save(*args, **kwargs)


class Destination(models.Model):
    d_province = models.ForeignKey(
        Province, on_delete=models.CASCADE, null=True, blank=True)
    d_district = models.ForeignKey(
        District, on_delete=models.CASCADE, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.d_province and self.location is None:
            raise ValidationError('You must provide a destination')

        elif self.d_province is not None and self.d_district is None:
            raise ValidationError('District is required for full address')
        elif self.d_district and self.location and self.d_province is None:
            self.d_district = None

        super().save(*args, **kwargs)

    def __str__(self):
        if self.location:
            return self.location

        return '%s-%s' % (self.d_province, self.d_district)

    def dest(self):
        """This function retrieve and format a destination
        whether using proince/distrit or just the entered location

        Returns:
            destination: formatted destination
        """
        if self.d_province:
            return '%s, %s' % (self.d_district, self.d_province)
        else:
            return "%s" % self.location


class PaymentBill(models.Model):
    number = models.CharField(_('RRA Nomero'), max_length=10)
    amount = models.CharField(_('Amafaranga yishyuwe'), max_length=6)
    rra_slip = models.FileField(
        upload_to='rra/%Y/', blank=True, null=True, verbose_name='Bordero ya Rwanda Revenue')


class TransportPermit(models.Model):
    officer = models.ForeignKey(
        'user.Officer', on_delete=models.SET_NULL, null=True, blank=True)
    code = models.CharField(_('Nomero'), max_length=255, blank=True,
                            null=True, editable=False)
    category = models.ForeignKey(
        Category, on_delete=models.SET_DEFAULT, default=1)
    requestor = models.ForeignKey(
        Requestor, on_delete=models.SET_NULL, null=True)
    vehicle = models.ForeignKey(
        TransportVehicle, on_delete=models.CASCADE, null=True)
    origin = models.ForeignKey(
        OriginLocation, on_delete=models.SET_NULL, null=True)
    destination = models.ForeignKey(
        Destination, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()

    start_date = models.DateField(
        auto_now_add=False, default=start_date_default)
    end_date = models.DateField(auto_now_add=False, default=end_date_default)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    prepared_by = models.ForeignKey(User, on_delete=models.CASCADE)
    approved_by = models.ForeignKey(
        Mayor, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name = "transport permit"
        verbose_name_plural = 'transport permits'

    def __str__(self):
        return "%s <%s>" % (self.requestor.names, self.code)

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = permit_code()
        d = self.origin.l_district
        try:
            officer = Officer.objects.get(district=d)

        except ObjectDoesNotExist as e:
            us, cr = User.objects.get_or_create(
                email='dfnro@%s.gov.rw' % d.name.lower(), first_name='DFNRO', last_name='%s' % d.name)
            if cr:
                us.set_password('trtruyrtgrtfver7363585665895yhycyf')
            officer, created = Officer.objects.get_or_create(
                user=us, district=d)
        self.officer = officer

user/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(
            self, email, first_name, last_name, password=None,
            commit=True):
        """
        Creates and saves a User with the given email, first name, last name
        and password.
        """
        if not email:
            raise ValueError(_('User must have an email address'))
        if not first_name:
            raise ValueError(_('User must have a first name'))
        if not last_name:
            raise ValueError(_('User must have a last name'))

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email, first name,
        last name and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            commit=False,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name=_('email address'), max_length=255, unique=True
    )
    # password field supplied by AbstractBaseUser
    # last_login field supplied by AbstractBaseUser
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        ),
    )

    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin

    date_joined = models.DateTimeField(
        _('date joined'), default=timezone.now
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        db_table = 'auth_user'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def __str__(self):
        return '{} <{}>'.format(self.get_full_name(), self.email)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    def get_short_name(self):
        return self.first_name

    def is_dfnro(self):
        try:
            if self.dfnro:
                return True
        except Exception:
            pass

        return False


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile', blank=True, null=True)
    biography = models.TextField(blank=True, null=True)
    district = models.ForeignKey(
        'permit.District', on_delete=models.SET_NULL, null=True, blank=True)
    sector = models.ForeignKey(
        'permit.Sector', blank=True, null=True, on_delete=models.SET_NULL)
    cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, blank=True)
    is_agent = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_agent and not self.district:
            raise ValueError('Agent must have a defined district')

        super().save(*args, **kwargs)

    def __str__(self):
        if self.is_agent:
            return "Agent: %s" % self.user.get_full_name()
        return '{}-Profile'.format(self.user.first_name)


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = Profile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=get_user_model())


class Officer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='dfnro', null=True)
    district = models.OneToOneField(
        'permit.District', on_delete=models.CASCADE, related_name='dfnro')

    def __str__(self):
        return "%s - %s " % (self.user.get_short_name(), self.district.name)

templates/forms/create-wizard.html
{% extends 'layout/base.html' %}

{% load static %}

{% block content %}



<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="col-md-12 mr-auto ml-auto">
        <!--      Wizard container        -->
        <div class="wizard-container">
            <div class="card card-wizard" data-color="primary" id="wizardProfile">
                <form action="" method="post" data-district-url="{% url 'ajax-load-districts' %}" id="hpform"
                    novalidate>
                    {% csrf_token %}
                    <!--        You can switch " data-color="primary" "  with one of the next bright colors: "green", "orange", "red", "blue"       -->
                    <div class="card-header text-center" data-background-color="orange">
                        <h3 class="card-title">
                            Gusaba uruhushya rwo gutwara ibikomoka kumashyamba.
                        </h3>
                        <h3 class="description">Uzuza iyi nyandiko neza.</h5>
                            <div class="wizard-navigation">
                                <ul class="nav nav-pills">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#about" data-toggle="tab" role="tab"
                                            aria-controls="about" aria-selected="true">
                                            <i class="now-ui-icons users_circle-08"></i> Uwaka uruhushya
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#account" data-toggle="tab" data-toggle="tab"
                                            role="tab" aria-controls="account" aria-selected="false">
                                            <i class="now-ui-icons ui-1_settings-gear-63"></i>Ingano yibitwawe nigihe
                                            bizatwarirwa
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#address" data-toggle="tab" data-toggle="tab"
                                            role="tab" aria-controls="address" aria-selected="false">
                                            <i class="now-ui-icons ui-1_email-85"></i> Aho biva naho bijya.
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#vehicle" data-toggle="tab" data-toggle="tab"
                                            role="tab" aria-controls="address" aria-selected="false">
                                            <i class="now-ui-icons ui-1_email-85"></i> Uko bizatwarwa
                                        </a>
                                    </li>
                                </ul>
                            </div>
                    </div>
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane show active" id="about">
                                <h5 class="info-text"> Imyirondoro y'usaba uruhushya</h5>
                                <div class="row justify-content-center">

                                    <div class="col-sm-6">
                                        {% for field in a_form %}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for=""
                                                        class="col-sm-4 col-form-label {% if field.field.required %}required {%endif %}">{{field.label}}</label>
                                                    <div class="col-sm-8">
                                                        {{field}}
                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                        {% endfor %}
                                    </div>

                                </div>

                            </div>
                            <div class="tab-pane fade" id="account">
                                <h5 class="info-text"> Ubwoko ningano yibisabirwa uruhushya </h5>
                                <div class="row justify-content-center">
                                    <div class="col-lg-10">

                                        {% for field in p_form %}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <label for=""
                                                        class="col-sm-4 col-form-label required">{{field.label}}</label>
                                                    <div class="col-sm-8">
                                                        {{field}}
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="address">
                                <div class="row justify-content-center">
                                    <div class="col-sm-12">
                                        <h5 class="info-text"> Injiza aho ibiti bizava </h5>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            {% for field in o_form %}
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group row">
                                                        <label for=""
                                                            class="col-sm-4 col-form-label {% if field.field.required %}required{%endif %}">{{field.label}}</label>
                                                        <div class="col-sm-8">
                                                            {{field}}
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>

                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <h5 class="info-text"> Injiza aho ibiti bizajya </h5>
                                    </div>
                                    {% for field in d_form %}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group row">
                                                <label for=""
                                                    class="col-sm-4 col-form-label {% if field.field.required %}required{%endif %}">{{field.label}}</label>
                                                <div class="col-sm-8">
                                                    {{field}}
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="vehicle">
                            <div class="row justify-content-center">
                                <div class="col-sm-12">
                                    <h5 class="info-text"> Amakuru ajyanye n'imodoka izabitwara. </h5>
                                </div>

                                {% for field in o_form %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group row">
                                            <label for=""
                                                class="col-sm-4 col-form-label {% if field.field.required %}required {%endif %}">{{field.label}}</label>
                                            <div class="col-sm-8">
                                                {{field}}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {% endfor %}
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="pull-right">
                            <input type='button' class='btn btn-next btn-fill btn-rose btn-wd' name='next'
                                value='Next' />
                            <input type='button' class='btn btn-finish btn-fill btn-rose btn-wd' name='finish'
                                value='Finish' />
                        </div>
                        <div class="pull-left">
                            <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous'
                                value='Previous' />
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
        </div>
        <!-- wizard container -->
    </div>
</div>

{% endblock content %}


{% block extra_js %}



<script>
    $(document).ready(function () {
        // Initialise the wizard
        demo.initNowUiWizard();
        setTimeout(function () {
            $('.card.card-wizard').addClass('active');
        }, 100);
        var $select = $("form select");
        $select.each(function () {
            $(this).addClass('custom-select w-90')
        });

    });
</script>
<script>
    $("#id_province").change(function () {
        var url = $("#hpform").attr("data-district-url");  // get the url of the `load_cities` view
        var countryId = $(this).val();
        $('#id_sector').val('');

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'province': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });
    });
    $("#id_district").change(function () {
        var url = $("#hpform").attr("data-district-url");  // get the url of the `load_cities` view
        var countryId = $(this).val();

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'district': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_sector").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });
    })
</script>

{% endblock extra_js %}

</body>

</html>

templates/forms/dropdown.html
<option value="">---------</option>
{% for opt in options %}
<option value="{{ opt.pk }}">{{ opt.name }}</option>
{% endfor %}