District_Forests/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dfm/urls.py
"""District_Forests URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
    1. Add an import:  from my_app import views
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('allauth.urls')),
    path('transport-permit/', include('permit.urls')),
    path('user/', include('user.urls')),
    path('harvesting-permit/', include('harvest.urls'))
]

permit/urls.py
from django.urls import path

from .views import (create_tp_view, dashboard_summary, edit_tp_permit,
                    generate_tpermit_pdf, load_district, permit_detail,
                    print_permit, tp_permit, transport_permit_single_view)

urlpatterns = [
    path('tp/', tp_permit, name='transport-permit-view'),
    path("print/<pk>/", print_permit, name='print-permit'),
    path('detail/<pk>/', permit_detail, name='permit-detail'),
    path('tp/pdf/<pk>/<code>/', generate_tpermit_pdf,
         name='transport-permit-print'),
    path('ajax/load-districts/', load_district, name='ajax-load-districts'),
    path('tp/new/', create_tp_view, name='tp-create-view'),
    path('tp/view/<pk>/', transport_permit_single_view, name='tp-single-view'),
    path('tp/edit/<pk>/', edit_tp_permit, name='edit-tp-view'),
    path('dashboard/summary/api/', dashboard_summary, name='dashboard-summary')
]

harvest/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from .utils import permit_code

User = get_user_model()


class HPRequestor(models.Model):
    cats = ((1, 'Leta'), (2, 'Akarere'), (3, 'Umurenge'), (4, 'Umuturage'))
    category = models.IntegerField(
        _('Usaba'), choices=cats, default=4)
    names = models.CharField(
        _('Amazina'), max_length=255, blank=False, null=False)
    nid = models.CharField(
        _('Indangamuntu'), max_length=21, blank=True, null=True)
    telephone = models.CharField(
        _('telephone'), max_length=15, blank=True, null=True)
    r_province = models.ForeignKey(
        'permit.Province', on_delete=models.SET, null=True, verbose_name='Intara')
    r_district = models.ForeignKey(
        'permit.District', on_delete=models.SET, null=True, verbose_name='Akarere')
    r_sector = models.ForeignKey(
        'permit.Sector', on_delete=models.SET, null=True, verbose_name='Umurenge')
    r_cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, verbose_name='Akagali')

    def __str__(self):
        return self.names


class TimberSpecies(models.Model):
    species = models.CharField(max_length=255, blank=False, null=False)
    width = models.FloatField(blank=True, null=True, default=13,
                              help_text='Andika ubugari muri centimeter', verbose_name='Umurambararo')
    height = models.FloatField(blank=True, null=True, default=15,
                               help_text='Andika uburebure muri metero', verbose_name='Uburebure')
    price = models.PositiveIntegerField(blank=True, null=True)


class ConstructionSpecies(models.Model):
    # ibiti bishingwa
    species = models.CharField(max_length=255, blank=True, null=False)
    width = models.FloatField(blank=True, null=True, default=13,
                              help_text='Andika ubugari muri centimeter', verbose_name='Umurambararo')
    height = models.FloatField(blank=True, null=True, default=15,
                               help_text='Andika uburebure muri metero', verbose_name='Uburebure')
    number = models.PositiveIntegerField(blank=True)


class Forest(models.Model):
    construction_species = models.ManyToManyField(
        ConstructionSpecies, blank=True, related_name='forests')
    timber_species = models.ManyToManyField(TimberSpecies, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    owner = models.CharField(max_length=255)
    area = models.FloatField()
    upi = models.CharField(max_length=10, blank=True, null=True)
    distance = models.FloatField(blank=True)
    # Address
    f_province = models.ForeignKey(
        'permit.Province', on_delete=models.SET, null=True, verbose_name='Intara')
    f_district = models.ForeignKey(
        'permit.District', on_delete=models.SET, null=True, verbose_name='Akarere')
    f_sector = models.ForeignKey(
        'permit.Sector', on_delete=models.SET, null=True, verbose_name='Umurenge')
    f_cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, verbose_name='Akagali')

    def __str__(self):
        return self.name

    def address(self):
        return "%s, %s, %s" % (self.f_cell, self.f_sector, self.f_district)


class FonerwaTaxes(models.Model):
    amount = models.FloatField(blank=True, null=True)
    bank = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    date = models.DateField(auto_now=False, default=timezone.now)

    def __str__(self):
        return self.amount


class DistrictTaxes(models.Model):
    amount = models.FloatField(blank=False)
    bank = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    date = models.DateField(auto_now=False, default=timezone.now)

    def __str__(self):
        return self.amount


class HarvestingGuidelines(models.Model):
    code = models.CharField(max_length=255, blank=True)
    text = models.TextField(blank=False, null=False)
    summary = models.TextField(auto_created=True, blank=True)

    def __str__(self):
        return self.code


class HarvestingPermit(models.Model):
    code = models.CharField(max_length=10, blank=True, null=True)
    requestor = models.ForeignKey(
        HPRequestor, verbose_name='Usaba', null=True, related_name='permits', on_delete=models.SET_NULL)
    dfnro = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)
    forest = models.ForeignKey(Forest, on_delete=models.SET_NULL, null=True)
    guidelines = models.ManyToManyField(HarvestingGuidelines, blank=True)
    start_date = models.DateField(auto_now_add=False)
    end_date = models.DateField(auto_now_add=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    date_approved = models.DateField(auto_now=False, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("harvesting_permit_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = permit_code()
        super().save(*args, **kwargs)

permit/views.py
import csv
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import View

from .forms import (AddPermitForm, DestinationForm, OriginForm, RequestorForm,
                    TransportVehicleForm)
from .models import (Category, Cell, District, Province, Sector,
                     TransportPermit, Village)
from .utils import generate_pdf_weasy, render_to_pdf

dirs = settings.BASE_DIR


@method_decorator(login_required, name='dispatch')
class TransportPermitView(View):
    def get(self, *args, **kwargs):
        user = self.request.user

        if user.is_dfnro():
            d = {'licenses': TransportPermit.objects.filter(
                officer=user.dfnro)}
            return render(self.request, 'dfnro-list.html', d)
        context = {
            'permits': TransportPermit.objects.filter(prepared_by=user).order_by('-created'),
            'form': AddPermitForm

        }
        return render(self.request, 'pages/tp-list.html', context)


tp_permit = TransportPermitView.as_view()


@login_required
def print_permit(request, pk):
    permit = get_object_or_404(TransportPermit, pk=pk)
    if permit:
        template = 'pages/print-permit.html'
        context = {'permit': permit}
        render_to_pdf(template, context)
    raise PermissionDenied


def permit_detail(request, pk):
    permit = get_object_or_404(TransportPermit, pk=pk)
    data = permit
    return JsonResponse(data)


def test_template(request):
    template = 'print/permit.html'
    return render(request, template)


def generate_tpermit_pdf(request, pk, *args, **kwargs):
    permit = get_object_or_404(TransportPermit, pk=pk)
    template = 'print/transport.html'
    context = {'permit': permit,
               'categories': Category.objects.all()}
    return generate_pdf_weasy(request, template, permit.code, context)


class CreateTPermitView(View):
    def get(self, *args, **kwargs):
        context = {
            'r_form': RequestorForm,
            'd_form': DestinationForm,
            'v_form': TransportVehicleForm,
            'o_form': OriginForm,
            'p_form': AddPermitForm
        }
        return render(self.request, 'forms/tp-create.html', context)

    def post(self, *args, **kwargs):
        r_form = RequestorForm(self.request.POST or None)
        d_form = DestinationForm(self.request.POST or None)
        v_form = TransportVehicleForm(self.request.POST or None)
        o_form = OriginForm(self.request.POST or None)
        p_form = AddPermitForm(self.request.POST or None)

        if r_form.is_valid() and d_form.is_valid() and v_form.is_valid() and o_form.is_valid() and p_form.is_valid():
            requestor = r_form.save()
            destination = d_form.save()
            origin = o_form.save()
            vehicle = v_form.save()
            permit = p_form.save(commit=False)
            permit.requestor = requestor
            permit.vehicle = vehicle
            permit.origin = origin
            permit.destination = destination
            permit.prepared_by = self.request.user
            permit.save()
            messages.success(self.request, 'New permit created successfully')
            return redirect(permit)

        context = {
            'r_form': r_form,
            'd_form': d_form,
            'v_form': v_form,
            'o_form': o_form,
            'p_form': p_form
        }
        return render(self.request, 'forms/tp-create.html', context)


create_tp_view = CreateTPermitView.as_view()


#
def load_district(request):
    country_id = request.GET.get('province')
    d_id = request.GET.get('district')
    s_id = request.GET.get('sector')
    c_id = request.GET.get('cell')
    if country_id is not None:
        cities = District.objects.filter(
            province_id=country_id).order_by('name')
        return render(request, 'forms/dropdown.html', {'options': cities})
    if d_id is not None:
        sectors = Sector.objects.filter(district_id=d_id).order_by('name')
        return render(request, 'forms/dropdown.html', {'options': sectors})
    if s_id is not None:
        cells = Cell.objects.filter(sector_id=s_id)
        return render(request, 'forms/dropdown.html', {'options': cells})
    if c_id is not None:
        cells = Village.objects.filter(cell_id=c_id)
        return render(request, 'forms/dropdown.html', {'options': cells})


def transport_permit_single_view(request, pk):
    permit = get_object_or_404(TransportPermit, pk=pk)
    context = {'permit': permit}
    return render(request, 'permit/tp/single.html', context)


def edit_tp_permit(request, pk):
    permit = get_object_or_404(TransportPermit, pk=pk)
    context = {
        'r_form': RequestorForm(instance=permit.requestor),
        'd_form': DestinationForm(instance=permit.destination),
        'v_form': TransportVehicleForm(instance=permit.vehicle),
        'o_form': OriginForm(instance=permit.origin),
        'p_form': AddPermitForm(instance=permit)
    }
    if request.method == 'POST':
        r_form = RequestorForm(request.POST, instance=permit.requestor)
        d_form = DestinationForm(request.POST, instance=permit.destination)
        v_form = TransportVehicleForm(request.POST, instance=permit.vehicle)
        o_form = OriginForm(request.POST, instance=permit.origin)
        p_form = AddPermitForm(request.POST, instance=permit)
        if r_form.is_valid() and d_form.is_valid() and v_form.is_valid() and o_form.is_valid() and p_form.is_valid():
            requestor = r_form.save()
            destination = d_form.save()
            origin = o_form.save()
            vehicle = v_form.save()
            permit = p_form.save()
            messages.success(
                request, 'Permit with %s code has been edited.' % permit.code)
            return redirect(permit)
        else:
            messages.error(request, 'Error in form')
            return render(request, 'forms/tp-create.html', context)

    return render(request, 'forms/tp-create.html', context)


def export_csv():
    import csv
    reader = csv.DictReader(open(os.path.join(dirs, "static/adm.csv")))
    for raw in reader:
        province = raw['PROVINCE']
        p_code = raw['PCODE'].strip('RW')
        district = raw['DISTRICT']
        d_code = raw['DCODE'].strip('RW')
        sector = raw['SECTOR']
        s_code = raw['SCODE'].strip('RW')
        cell = raw['CELL']
        c_code = raw['CCODE'].strip('RW')

        prov, created = Province.objects.get_or_create(
            code=p_code, name=province)
        dist, created = District.objects.get_or_create(
            code=d_code, name=district, province=prov)
        sec, created = Sector.objects.get_or_create(
            code=s_code, name=sector, district=dist)
        cel, created = Cell.objects.get_or_create(
            name=cell, code=c_code, sector=sec)


class DashboardSummary(View):
    def get(self, *args, **kwargs):
        data = {}
        return JsonResponse(data)

dashboard_summary = DashboardSummary.as_view()

templates/print/permits.html
{% extends 'layout/base.html' %}

templates/print/transport.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transport Permit</title>
    <link rel="stylesheet" href="/static/css/main.css" class="css">
    <style>
        .normal {
            font-size: 10pt;
        }

        ol li {
            margin-bottom: 2pt;
        }
    </style>
</head>

<body>
    <div class="page-wrapper transport">
        <div class="heading">
            <div class="header1">REPUBULIKA Y'U RWANDA</div>
            <div class="header1">INTARA Y'AMAJYARUGURU</div>
            <div class="symbol"><img src="/static/img/favicon.jpg" alt="" height="50px" width="50px"></div>
            <div class="header1 underline">AKARERE KA RULINDO</div>
            <div class="header1">REF: <span class="capitalize italic">Ubuhinzi n'Umutungo Kamere</span></div>
        </div>
        <div class="head-title">
            <div class="header1 text-center underline">URUHUSHYA RWO GUTWARA</div>
            <div class="row text-center">
                <div class="header1 text-center underline capitalize">

                    {% for cat in categories %}

                    {% if not cat == permit.category %}
                    <strike>{{cat.get_name_display}}/</strike>
                    {% else %}
                    {{cat.get_name_display}}/
                    {% endif %}

                    {% endfor %}
                </div>
                <div class="normal text-center underline pl-10">No: {{permit.code}}</div>
            </div>

        </div>
        <div class="body">
            <ol class="normal">
                <!-- Usaba uruhushya -->
                <li>AMAZINA: <span class="bold normal capitalize">{{permit.requestor.names}}
                        {% if permit.requestor.telephone %}
                        &nbsp;({{permit.requestor.telephone}})
                        {% endif %}
                    </span></li>
                <li>INDANGAMUNTU: <span class="bold normal">{{permit.requestor.nid}}</span></li>
                <li>AHO ABARIZWA:
                    <ul class="w-60 pl-10">
                        <li><span class="w-50 pull-left">AKAGALI:</span> <span
                                class="bold">{{permit.requestor.r_cell}}</span></li>
                        <li><span class="w-50 pull-left">UMURENGE:</span> <span
                                class="bold">{{permit.requestor.r_sector}}</span></li>
                        <li><span class="w-50 pull-left">AKARERE:</span> <span
                                class="bold">{{permit.requestor.r_district}}</span></li>
                        <li><span class="w-50 pull-left">INTARA:</span> <span
                                class="bold">{{permit.requestor.r_province}}</span></li>
                    </ul>
                </li>

                <!-- IBISABIRWA URUHUSHYA -->
                <li>INGANO Y'IBITWAWE: <span class="bold">{{permit.category.get_name_display}}
                        ({{permit.category.measure}} <span class="bold">{{permit.quantity}}</span>)</span></li>
                <li>AHO BIVA:
                    <!-- Origin location -->
                    <ul class="w-60 pl-10">
                        <li><span class="w-50 pull-left">AKAGALI:</span> <span
                                class="bold">{{permit.origin.l_cell}}</span></li>
                        <li><span class="w-50 pull-left">UMURENGE:</span> <span
                                class="bold">{{permit.origin.l_sector}}</span></li>
                        <li><span class="w-50 pull-left">AKARERE:</span> <span
                                class="bold">{{permit.origin.l_district}}</span></li>
                    </ul>
                </li>

                <li>AHO BIJYA: <span class="bold">{{permit.destination.dest}}</span></li>
                <!-- Imodoka izakoreshwa -->

                <li>IMODOKA IZAKORESHWA: <span class="bold">{{permit.vehicle.vehicle}}</span>
                    <ul class="w-80 pl-10">
                        <li><span class="w-30 pull-left">No ZA PULAKI:</span> <span
                                class="bold license">{{permit.vehicle.plate}}</span></li>
                        <li><span class="w-30 pull-left">IZINA RY'UMUSHOFERI:</span> <span
                                class="bold">{{permit.vehicle.driver}}</span>
                        </li>
                        <li><span class="w-30 pull-left">TELEFONI YE:</span> <span
                                class="bold telephone">{{permit.vehicle.driver_tel}}</span></li>

                        <li><span class="w-30 pull-left">INDANGAMUNTU:</span> <span
                                class="bold nid">{{permit.vehicle.nid}}</span></li> <br>
                    </ul>
                </li>

                <li>IGIHE URUHUSHYA RUZAMARA: <span class="bold">{{permit.permit_period}} <span class="date">Kuva
                            {{permit.start_date|date:"d-m-Y"}}
                            kugeza
                            {{permit.end_date|date:"d-m-Y"}}</span></span></li>
                <br>
            </ol>
        </div>

        <div class="row p-1 normal">
            Bikorewe i <strong>RULINDO</strong>, kuwa <strong>{%now "d m Y"%}</strong>
        </div>
        <div class="row pt-1 mb-5">
            <div class="w-50 pull-left">
                <span class="bold underline normal ">Biteguwe na:</span>
            </div>
            <div class="w-50 pull-right">
                <span class="bold underline normal ">Byemejwe na:</span>
            </div>
        </div>
        <div class="row pt-3" style="margin-top: 10px;">
            <div class="w-50 pull-left">
                <h6 class="normal p-0 m-0">SALAMA Fides</h6>
                <h6 class="normal capitalize">Umukozi ushinzwe amashyamba n'umutungo kamere mu karere ka Rulino
                </h6>
            </div>
            <div class="w-50 pull-right">
                <h6 class="normal p-0 m-0">KAYIRANGA Emmanuel</h6>
                <h6 class="normal">Umuyobozi w'Akrere ka Rulindo</h6>
            </div>
        </div>
        <div class="normal" style="margin-top: 10px;">
            <ul><span class="bold">ICYITONDERWA:</span>
                <li class="pl-5"><i class="arrow right mr-3"></i>Uru ruhushya rukoreshwa kukintu kimwe gusa</li>
                <li class="pl-5"><i class="arrow right mr-3"></i>Usaba uruhushya yerekana kopi y'uruhushya/impushya
                    rwo/zo gutema</li>
                <li class="pl-5"><i class="arrow right mr-3"></i>Uru ruhushya rwemerwa gusa iyo ari umwimerere
                    (Original)</li>
                <li class="pl-5"><i class="arrow right mr-3"></i><span>Uhawe uru ruhushya yiyemeje gukurikiza itegeko
                        n’amabwiriza ariho mu Gihugu arebana n’ubusugire bw’amashyamba( itegeko No 47bis/2013 ryo ku wa
                        28/06/2013 rigena imicungire n’imikoreshereze y’amashyamba mu Rwanda).</span></li>
            </ul>
        </div>
    </div>
</body>

</html>