District_Forests/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dfm/urls.py
"""District_Forests URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
    1. Add an import:  from my_app import views
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('allauth.urls')),
    path('transport-permit/', include('permit.urls')),
    path('user/', include('user.urls')),
    path('harvesting-permit/', include('harvest.urls'))
]

user/urls.py
from django.urls import path
from .views import profile_view
urlpatterns = [
    path('profile/', profile_view, name='user-profile')
]

harvest/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from .utils import permit_code

User = get_user_model()


class HPRequestor(models.Model):
    cats = ((1, 'Leta'), (2, 'Akarere'), (3, 'Umurenge'), (4, 'Umuturage'))
    category = models.IntegerField(
        _('Usaba'), choices=cats, default=4)
    names = models.CharField(
        _('Amazina'), max_length=255, blank=False, null=False)
    nid = models.CharField(
        _('Indangamuntu'), max_length=21, blank=True, null=True)
    telephone = models.CharField(
        _('telephone'), max_length=15, blank=True, null=True)
    r_province = models.ForeignKey(
        'permit.Province', on_delete=models.SET, null=True, verbose_name='Intara')
    r_district = models.ForeignKey(
        'permit.District', on_delete=models.SET, null=True, verbose_name='Akarere')
    r_sector = models.ForeignKey(
        'permit.Sector', on_delete=models.SET, null=True, verbose_name='Umurenge')
    r_cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, verbose_name='Akagali')

    def __str__(self):
        return self.names


class TimberSpecies(models.Model):
    species = models.CharField(max_length=255, blank=False, null=False)
    width = models.FloatField(blank=True, null=True, default=13,
                              help_text='Andika ubugari muri centimeter', verbose_name='Umurambararo')
    height = models.FloatField(blank=True, null=True, default=15,
                               help_text='Andika uburebure muri metero', verbose_name='Uburebure')
    price = models.PositiveIntegerField(blank=True, null=True)


class ConstructionSpecies(models.Model):
    # ibiti bishingwa
    species = models.CharField(max_length=255, blank=True, null=False)
    width = models.FloatField(blank=True, null=True, default=13,
                              help_text='Andika ubugari muri centimeter', verbose_name='Umurambararo')
    height = models.FloatField(blank=True, null=True, default=15,
                               help_text='Andika uburebure muri metero', verbose_name='Uburebure')
    number = models.PositiveIntegerField(blank=True)


class Forest(models.Model):
    construction_species = models.ManyToManyField(
        ConstructionSpecies, blank=True, related_name='forests')
    timber_species = models.ManyToManyField(TimberSpecies, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    owner = models.CharField(max_length=255)
    area = models.FloatField()
    upi = models.CharField(max_length=10, blank=True, null=True)
    distance = models.FloatField(blank=True)
    # Address
    f_province = models.ForeignKey(
        'permit.Province', on_delete=models.SET, null=True, verbose_name='Intara')
    f_district = models.ForeignKey(
        'permit.District', on_delete=models.SET, null=True, verbose_name='Akarere')
    f_sector = models.ForeignKey(
        'permit.Sector', on_delete=models.SET, null=True, verbose_name='Umurenge')
    f_cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, verbose_name='Akagali')

    def __str__(self):
        return self.name

    def address(self):
        return "%s, %s, %s" % (self.f_cell, self.f_sector, self.f_district)


class FonerwaTaxes(models.Model):
    amount = models.FloatField(blank=True, null=True)
    bank = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    date = models.DateField(auto_now=False, default=timezone.now)

    def __str__(self):
        return self.amount


class DistrictTaxes(models.Model):
    amount = models.FloatField(blank=False)
    bank = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    date = models.DateField(auto_now=False, default=timezone.now)

    def __str__(self):
        return self.amount


class HarvestingGuidelines(models.Model):
    code = models.CharField(max_length=255, blank=True)
    text = models.TextField(blank=False, null=False)
    summary = models.TextField(auto_created=True, blank=True)

    def __str__(self):
        return self.code


class HarvestingPermit(models.Model):
    code = models.CharField(max_length=10, blank=True, null=True)
    requestor = models.ForeignKey(
        HPRequestor, verbose_name='Usaba', null=True, related_name='permits', on_delete=models.SET_NULL)
    dfnro = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)
    forest = models.ForeignKey(Forest, on_delete=models.SET_NULL, null=True)
    guidelines = models.ManyToManyField(HarvestingGuidelines, blank=True)
    start_date = models.DateField(auto_now_add=False)
    end_date = models.DateField(auto_now_add=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    date_approved = models.DateField(auto_now=False, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("harvesting_permit_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = permit_code()
        super().save(*args, **kwargs)

user/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(
            self, email, first_name, last_name, password=None,
            commit=True):
        """
        Creates and saves a User with the given email, first name, last name
        and password.
        """
        if not email:
            raise ValueError(_('User must have an email address'))
        if not first_name:
            raise ValueError(_('User must have a first name'))
        if not last_name:
            raise ValueError(_('User must have a last name'))

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email, first name,
        last name and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            commit=False,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name=_('email address'), max_length=255, unique=True
    )
    # password field supplied by AbstractBaseUser
    # last_login field supplied by AbstractBaseUser
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        ),
    )

    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin

    date_joined = models.DateTimeField(
        _('date joined'), default=timezone.now
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        db_table = 'auth_user'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def __str__(self):
        return '{} <{}>'.format(self.get_full_name(), self.email)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    def get_short_name(self):
        return self.first_name

    def is_dfnro(self):
        try:
            if self.dfnro:
                return True
        except Exception:
            pass

        return False


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile', blank=True, null=True)
    biography = models.TextField(blank=True, null=True)
    district = models.ForeignKey(
        'permit.District', on_delete=models.SET_NULL, null=True, blank=True)
    sector = models.ForeignKey(
        'permit.Sector', blank=True, null=True, on_delete=models.SET_NULL)
    cell = models.ForeignKey(
        'permit.Cell', on_delete=models.SET_NULL, null=True, blank=True)
    is_agent = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_agent and not self.district:
            raise ValueError('Agent must have a defined district')

        super().save(*args, **kwargs)

    def __str__(self):
        if self.is_agent:
            return "Agent: %s" % self.user.get_full_name()
        return '{}-Profile'.format(self.user.first_name)


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = Profile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=get_user_model())


class Officer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='dfnro', null=True)
    district = models.OneToOneField(
        'permit.District', on_delete=models.CASCADE, related_name='dfnro')

    def __str__(self):
        return "%s - %s " % (self.user.get_short_name(), self.district.name)

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from permit.models import Cell, Sector

from .models import Profile

User = get_user_model()


class CreateUserForm(UserCreationForm):
    """
    New User Form. Requires password confirmation.
    """
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sector'].queryset = Sector.objects.none()
        self.fields['cell'].queryset = Cell.objects.none()
        if 'district' in self.data:
            try:
                d_id = int(self.data.get('district'))
                self.fields['sector'].queryset = Sector.objects.filter(
                    district_id=d_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.district is not None:
            self.fields['sector'].queryset = self.instance.district.sectors.order_by(
                'name')
        if 'sector' in self.data:
            try:
                d_id = int(self.data.get('sector'))
                self.fields['cell'].queryset = Cell.objects.filter(
                    sector_id=d_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.sector is not None:
            self.fields['cell'].queryset = self.instance.sector.cells.order_by(
                'name')
    class Meta:
        model = Profile
        fields = ['image', 'biography', 'district', 'sector', 'cell']
        widgets = {
            'biography': forms.Textarea(attrs={'rows': 3, 'cols': 60}),
        }


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']

user/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import View

from .forms import UpdateProfileForm, UpdateUserForm
from .models import Profile


@method_decorator(login_required, name='dispatch')
class UserProfile(View):
    def get(self, *args, **kwargs):
        user = self.request.user
        profile, created = Profile.objects.get_or_create(user=user)
        context = {
            'form': UpdateUserForm(instance=user),
            'p_form': UpdateProfileForm(instance=profile)
        }

        return render(self.request, 'user/profile.html', context)

    def post(self, *args, **kwargs):
        user = self.request.user
        profile, created = Profile.objects.get_or_create(user=user)
        form= UpdateUserForm(self.request.POST or None, instance=user)
        p_form = UpdateProfileForm(self.request.POST or None, self.request.FILES or None, instance=profile)

        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.info(self.request, 'Your profile has been successfully updated')
            return redirect('user-profile')
        else:
            messages.error(self.request, 'Please fill the form correctly')
            return redirect('user-profile')


profile_view = UserProfile.as_view()

templates/user/profile.html
{% extends 'layout/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Profile Page {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet" href="/static/css/cropper.min.css" class="css">
{% endblock stylesheets %}

{% block content %}

<div class="panel-header panel-header-sm">
</div>
<div class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Profile: {{ request.user.get_full_name }}</h5>
                </div>
                <div class="card-body">
                    <form method="post" action="." enctype="multipart/form-data" data-district-url="{% url 'ajax-load-districts' %}" id="pform">
                        {% csrf_token %}

                        {% for field in p_form %}

                        {% if field not in p_form.visible_fields %}
                        {{field}}
                        {% endif %}


                        {% endfor %}

                        <div class="row">
                            <div class="col-md-5 pr-1">
                                <div class="form-group">
                                    <label>UserEmail (disabled)</label>
                                    <input type="text" class="form-control" disabled="" placeholder="E-mail"
                                        value="{{ request.user.email }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>First Name</label>
                                    {% render_field form.first_name class="form-control"%}
                                </div>
                            </div>
                            <div class="col-md-6 pl-1">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    {% render_field form.last_name class="form-control"%}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 pr-1">
                                <div class="form-group">
                                    <label>Akarere</label>
                                    {% render_field p_form.district class="custom-select"%}
                                </div>
                            </div>
                            <div class="col-md-4 pl-1">
                                <div class="form-group">
                                    <label>Umurenge</label>
                                    {% render_field p_form.sector class="custom-select"%}
                                </div>
                            </div>
                            <div class="col-md-4 pl-1">
                                <div class="form-group">
                                    <label>Akagali</label>
                                    {% render_field p_form.cell class="custom-select"%}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>About Me</label>
                                    {% render_field p_form.biography class="form-control"%}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 pr-1">
                                <div class="custom-file" id="image_input">
                                    <input type="file" class="custom-file-input" name="image" id="id_image">
                                    <label for="id_image" class="custom-file-label" id="image_label">Profile
                                        Picture</label>
                                </div>

                                {% if user.profile.image %}

                                <div class="custom-control custom-checkbox my-1 mr-sm-2" id="clear_id">
                                    <br>
                                    <input type="checkbox" name="image-clear" id="image-clear_id"
                                        class="custom-control-input">
                                    <label for="image-clear_id" class="custom-control-label">Remove Current
                                        Image</label>
                                </div>

                                {% endif %}


                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 pr-1">
                                <input type="submit" value="Update" class="btn btn-info">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <!-- USER PROFILE VIEW -->
            {% include 'includes/profile.html' %}
            <!-- // USER PROFILE -->
        </div>
    </div>
</div>


<div class="modal fade" id="modalCrop" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" height='30'>
                <h4 class="modal-title text-center">Crop the photo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body overflow-auto" style="max-height: 60%;">
                <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                    <button type="button" class="btn btn-default js-zoom-in">
                        <i class="fas fa-search-plus"></i>
                    </button>
                    <button type="button" class="btn btn-default js-zoom-out">
                        <i class="fas fa-search-minus"></i>
                    </button>
                </div>

                <button type="button" class="btn btn-info js-crop-and-upload">Crop and continue</button>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block extra_js %}
<script src="/static/js/cropper.min.js"></script>
<script>
    $(document).ready(function () {
        $("#id_image").change(function () {
            let filePath = $(this)[0].files[0].name;
            $("#image_label").text(filePath);
            $('#clear_id').hide();

            var reader = new FileReader();
            reader.onload = function (e) {
                $("#image").attr("src", e.target.result);
                //$("#profileImage").attr('src', e.target.result);
                $("#modalCrop").modal("show");
            }
            reader.readAsDataURL(this.files[0]);
        }
        );

        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1 / 1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                rotatable: false,

                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#modalCrop").modal("hide");

            //$("#formUpload").submit();
        });



        $("#image-clear_id").change(function () {
            if (this.checked) {
                $('#image_input').hide(500);
            } else {
                $('#image_input').show(500)
            }
        });
        $('#account_delete').click(function () {
            let result = confirm('Are You Sure You Want to delete Your Accounts');
            if (result == true) {
                console.log('Go');
            } else {
                console.log('No');
            }
        })
    })
</script>
<script>
    $("#id_district").change(function () {
        var url = $("#pform").attr("data-district-url");  // get the url of the `load_cities` view
        var ID = $(this).val();
        $('#id_cell').val('');
        //$('#id_r_village').val('');

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'district': ID       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_sector").html(data); // replace the contents of the city input with the data that came from the server
            }
        });
    })
    $("#id_sector").change(function () {
        var url = $("#pform").attr("data-district-url");  // get the url of the `load_cities` view
        var ID = $(this).val();
        //$('#id_r_village').val('');

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'sector': ID       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_cell").html(data); // replace the contents of the city input with the data that came from the server
            }
        });
    })

</script>
{% endblock extra_js %}